export enum TournamentRegistrationError {
    NO_ERROR = 0,
    TOURNAMENT_INSTANCE_NOT_FOUND = 30001,
    TOURNAMENT_REGISTRATION_NOT_ENOUGH_POINTS = 30002,
    TOURNAMENT_INSTANCE_NOT_IN_STATE = 30003,
    TOURNAMENT_ALREADY_REGISTERED = 30004,
    TOURNAMENT_USER_DONT_MATCH_CONDITIONS = 30005,
    TOURNAMENT_USER_NOT_REGISTERED = 30006,
    TOURNAMENT_CANT_CHANGE_REGISTRATION_STATUS = 30007,
    TOURNAMENT_MAX_REGISTRATIONS_REACHED = 30008,
}
