export enum MarketsValueType {
    HomeTeam = '1',
    AwayTeam = '2',
    Draw = 'x',
    HomeTeamHomeTeam = '1/1',
    HomeTeamDraw = '1/x',
    HomeTeamAwayTeam = '1/2',
    DrawHomeTeam = 'x/1',
    DrawDraw = 'x/x',
    DrawAwayTeam = 'x/2',
    AwayTeamHomeTeam = '2/1',
    AwayTeamDraw = '2/x',
    AwayTeamAwayTeam = '2/2',
    Yes = 'yes',
    No = 'no',
    Odd = 'odd',
    Even = 'even',
    HomeOdd = '1/odd',
    HomeEven = '1/even',
    AwayOdd = '2/odd',
    AwayEven = '2/even',
}
