export enum ClassId {
    GET_LABEL_INFO = 3,
    GET_LABEL_INFO_RESPONSE = 4, 
    IDENTIFY = 5,
    IDENTIFY_RESPONSE = 6,
    EVENT = 9,
    EVENT_RESPONSE = 10,    

    GET_TRANSLATIONS_REQUEST = 13,
    GET_TRANSLATIONS_RESPONSE = 14,

    CHANGE_USERNAME = 159,
    CHANGE_USERNAME_RESPONSE = 160,

    SAW_GET_SPINS_REQUEST = 700,
    SAW_GET_SPINS_RESPONSE = 701,
    SAW_DO_SPIN_REQUEST = 702,
    SAW_DO_SPIN_RESPONSE = 703,
    SAW_AKNOWLEDGE_REQUEST = 704,
    SAW_AKNOWLEDGE_RESPONSE = 705,

    SAW_SPINS_COUNT_PUSH = 706,
    SAW_SHOW_SPIN_PUSH = 707,

    UNSUPPORTED_COMMAND = 99999.
}